---
name: "SHORTCODE-XX: SHORT TITLE"
description: "DESCRIPTION"
title: "SHORTCODE-XX: TITLE"
labels:
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Bitte fülle die folgenden Abschnitte aus falls Anpassungen erforderlich sind. Standard-User-Story unten.
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Als Nutzer*in, Als MA Filminstitut, Als Projektteam, ...
      value: |
    validations:
      required: true
  - type: textarea
    id: kontext
    attributes:
      label: Kontext
      value: |
  - type: textarea
    id: akzeptanzkriterien
    attributes:
      label: Akzeptanzkriterien
      value: |
    validations:
      required: true
  - type: textarea
    id: technische-notizen
    attributes:
      label: Technische Notizen / Implementation Hints
      description: Hinweise zu Datenquellen, Pagination, Cache etc.
  - type: checkboxes
    id: quality-gates
    attributes:
      label: Qualitäts-Checks
      options:
    validations:
      required: false
  - type: textarea
    id: test-hinweise
    attributes:
      label: Testfälle (optional)
      description: Zusätzliche Testfälle oder Edge Cases
  - type: textarea
    id: links
    attributes:
      label: Referenzen / Links
      description: Relevante frühere Issues, PRs, Dokumentation
projects:
  - AV-EFI/1
---
